// Generated by https://quicktype.io

export class Carrera {
    nombreCarrera: string;
    codigoCarrera: string;
    idInstituto:   number;
    siglas:        string;

    constructor() {
        this.nombreCarrera = "";
        this.codigoCarrera = "";
        this.idInstituto = 0;
        this.siglas = "";
    }
}
