// Generated by https://quicktype.io

export class Instituto {
    nombreInstituto: string;
    codigoInstituto: string;

    constructor(){
        this.nombreInstituto = "";
        this.codigoInstituto = "";
    }
}
